### ISSUE TITLE
str_match_all gets confused when there are nested groups

### ISSUE THREAD

**Issue by oganm** [coolbutuseless/minilexer#1]
If you try to define a token that includes groups, `str_match_all` gets confused as it tries to return matches for all groups including the subgroups. See

```r
minilexer::lex('abcd',patterns = c(g1 = '(a)|(b)',g2 = 'c'))
```
as an example, which returns

```r
      g1       g2 .missing     <NA> 
     "a"      "b"      "c"      "d" 
```

**Comment by coolbutuseless** [comment]
Due to the way patterns are handled, you can really only have one "()" per pattern.

Would the following work for you:

```r
minilexer::lex('abcd',patterns = c(g1 = '(a|b)',g2 = 'c'))
```

**Comment by coolbutuseless** [comment]
GIven the simplicity of this lexer, and its use of string_match_all(), I don't think I will ever change it to support multiple groups in this fashion.

I've added an explicit check to thrown an error if this sort of pattern is used.  (see https://github.com/coolbutuseless/minilexer/commit/b2d1378d6a5070deb2280516543e170a68d57e1c)
