### ISSUE TITLE
Chaining tokens and ICU

### ISSUE THREAD

**Issue by oganm** [coolbutuseless/minilexer#2]
I want to create tokens that depend on other tokens to facilitate definition of more complex grammars. For this I wrote the function below:

```r
generatePatterns = function(patterns, # final outputs here 
                            helperPatterns = NULL, # intermediate patterns that won't be returned here
                            .open= '{', .close = '}'){
    
    for (i in seq_along(helperPatterns)){
        helperPatterns[[i]] = with(helperPatterns[1:i],
                                   {glue(helperPatterns[[i]],
                                         .open = .open,
                                         .close = .close)})
    }
    
    for (i in seq_along(patterns)) {
        patterns[[i]] = 
            with(c(helperPatterns, patterns[1:i]),
             {glue(patterns[[i]],
                   .open = .open, 
                   .close =.close)
             })
        }

    return(unlist(patterns))
}
```

The idea is to nest regexes for different terms within each other. For instance I wanted to lexify a RPG dice syntax like `6d20`, I could do something like

``` r
# these are patterns that won't be matched in the final results
helperPatterns = list(
    integer = '[0-9]',
    number = '{integer}+'
)

# these are patterns we are interested in
patterns = list(
    diceCore = '(?<={integer})[dD](?={integer})',
    diceCount = '{number}(?={diceCore})',
    diceSide = '(?<={diceCore}){number}',
)

patterns = generatePatterns(patterns,helperPatterns)
```
```r
                            diceCore                            diceCount                             diceSide 
           "(?<=[0-9])[dD](?=[0-9])"  "[0-9]+(?=(?<=[0-9])[dD](?=[0-9]))" "(?<=(?<=[0-9])[dD](?=[0-9]))[0-9]+" 
```

This approach should theoretically work but due to limitations of ICU (which is used by stringr) the resulting expressions with nested lookbehinds in them do not work (`diceSide` in this case). Currently working on a version that allows using PCRE engine using base R which is a little annoying to work with. Noticed #1 when working on this. If interested, there might be a pull request soonish™. The solution will probably involve manually going through the matching groups rather than merging them into a single pattern so it'll probably offer a way to solve #1

**Comment by coolbutuseless** [comment]
Hi @oganm,

Could you post a bit more detail on what you're trying to achieve?  E.g. a sample of the input and output you expect?

I feel you may be asking too much of this very simple lexer :)

My approach, given the simplicity of minilexer, would be to capture the dice as a whole token, and then do specific parsing on it later.

```
text     <- "roll a 6d20 now"
patterns <- c(dice = "\\d+[dD]\\d+", word="\\w+", whitespace="\\s+")
lex(text, patterns)
```

**Comment by oganm** [comment]
Yes I imagine this is not the standard use here. What I was trying to do was to parse the dice string as is. Dice rolls has a syntax that may look more like `6d12sdh3ro<3r<2`. I already have a parser for the format using basic regex. What I hope to gain from this was to write it in a more maintainable way with proper error detection and applicable to other things such as file parsing in an arbitrary future. The other more complex parser packages are probably the "right" tools for the job but for a simple thing like this I assumed it'd work fine. I am also looking into those. 

In general I am curious about writing general purpose parsers and playing around. Nothing particularly of importance.

**Comment by coolbutuseless** [comment]
No action to take. closing issue.
